### PR TITLE
Move all constants to file

### PR DESCRIPTION
**Pull request by mdcfe**
Move all the constants at the top of the index to a separate module, and use destructuring to define them as necessary in the index. This will facilitate splitting the code into smaller, more logical modules later on.

### CODE REVIEW

**Comment by mdcfe** [comment]
+1

**Comment by Smittyvb** [comment]
+1

**Comment by syvb** [comment]
You can remove changing the repo when not in production (line 8 and 9). That was just a test repo I used for development.

**Comment by mdcfe** [comment]
@Smittyvb Okay, will do.

**Comment by syvb** [comment]
This has merge conflicts, even if we have enough votes, ChaosBot will fail to merge this.

**Comment by Kroppeb** [comment]
If you would merge this
https://github.com/Chaosthebot/chaos2/pull/14
Would this then be able to merge or do we need a separate pull request for that?

**Pull request closed without merging**
